apiVersion: v1
kind: ConfigMap
metadata:
  name: apoia-config
  labels:
    app: apoia
    part-of: pdpj-apoia
data:
  NEXTAUTH_URL_INTERNAL: "http://localhost:80"
  NEXTAUTH_URL: "http://apoia.pdpj.jus.br"
  ###NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
  NEXT_PUBLIC_BASE_URL: "http://apoia.pdpj.jus.br"

  ###JWT_SECRET: ${JWT_SECRET}
  JWT_ISSUER: "apoia.trf2.jus.br"
  JWT_AUDIENCE: "apoia.trf2.jus.br"

  ###PWD_SECRET: ${PWD_SECRET}

  CONFIDENTIALITY_LEVEL_MAX: "0"
  VERCEL: "1"
  VERCEL_ENV: "development"

  DB_CLIENT: "pg"
  ###DB_HOST: "postgres.comum"
  DB_PORT: "5432"
  ###DB_USER: ${DB_USER}
  ###DB_PASSWORD: ${DB_PASSWORD}
  DB_DATABASE: "pdpj_apoia"

  ###KEYCLOAK_CREDENTIALS_SECRET: ${KEYCLOAK_CREDENTIALS_SECRET}
  KEYCLOAK_ISSUER: "https://sso.cloud.pje.jus.br/auth/realms/pje"

  APP_CODE: "ApoIA"
  APP_HOST: "apoia.pdpj.jus.br"
  APP_PORT: "80"
  APP_REGISTRY_HOST: "discovery.prd.cnj.cloud/eureka"
  #APP_REGISTRY_PORT: "8761"

  DATALAKE_API_URL: "https://api-processo-integracao.data-lake.pdpj.jus.br/processo-api/api/v1"

  GOOGLE_ANALYTICS_ID: "G-YT91JXZFP9"
  WOOTRIC_ACCOUNT_TOKEN: "NPS-8c9fb077"
  MODERATOR_ENCRYPTED: "6fb5e166b1f148469871b792d4ac442d2fcd28a1d022c34c3dcd4d36f794452b611956908170cae6b7ab814bee30422a4c366a85f436c83266e566ac77ce170df7ea44bd48d69badf37a1980e850697fe29dd9a5c8a88da04fd1200f6b7a56fdca6719dce0e28c676555a205ccffb2f117fc38ab4689d3"
  
  # MODEL: "gpt-4.1-nano"

  # TRF2
  # TRIBUNAL_4_MODEL: "azure-gpt-4.1,azure-gpt-4.1-mini,gemini-2.5-pro,gemini-2.5-flash,aws-us.anthropic.claude-sonnet-4-20250514-v1:0"
  TRIBUNAL_4_MODEL: "gemini-2.5-flash"
  TRIBUNAL_4_AZURE_API_KEY_ENCRYPTED: "d2f46cf5d0d9f9d39d69ac24a51beedf8deaecc19e2627c80c5da8813ec7cd33a4d396c5adcab20992170d3dc5c1fbc749dd292ff441da22769e8cfe83bce23329f1f5743e57c9e3311280ee41790f3c296e785cf9d5d36d72754085c6489b6e648aefb813afc68b48bca241a9d30a55f292f61200e50eb9529b82735578432fb7e680046baee1089f377686366229267422d23194507992fcc4f6d9edf5492f1401c8d3de70bd450bec39c0f45c469c56e32da8"
  TRIBUNAL_4_AZURE_RESOURCE_NAME: "apoia-instance"
  TRIBUNAL_4_GOOGLE_API_KEY_ENCRYPTED: "ceae11b21146b69a33462c8108798f3d58e2e7803dd7534922f20396cca7c12ca0d4a5816ff6b0b59d534a65e5ae6467e2466c163389c86e2d09d884884f27751b4239895126ac02b2913f2077a6283d10924838a262df47cea42e39c3f7f3a58dd3dded0d7413ac6f9f47e3c8d54544deabb99cc9a6bbe84cc78ab7ee56d7b8d7735b1c5161ec"
  TRIBUNAL_4_AWS_SECRET_ACCESS_KEY_ENCRYPTED: "4632e0ee5d717b24e797d4eec47bf0926b490b5f4a943c77c3227ebbe14cde125f638534e9605ff1dc2eb5fdc447e4aaec21df13e77dcd2ac89b170400f43ba76f83ab97329cc01c7a099dd481f564c7a12db936e990a96ac83da4e648bdc46d13cfe0ef7370f2e8d14e95ec5655a79699a7373bfab499b67b849534cfba328d95f90ed76f4fb0fa"
  TRIBUNAL_4_AWS_ACCESS_KEY_ID: "AKIARRV6RGMYOBACMOF4"
  TRIBUNAL_4_AWS_REGION: "us-east-2"
  TRIBUNAL_4_MODEL_ALLOWED_USERS_ENCRYPTED: "a8d9b39871a17024a53da345748f7844d9304eab76d070536d6ae56ee6da1e4c791e5bbd370fa277cd0bfb6d99d18553ab60a2e1fd61dd144bb6d864db94445050d87dd1eb13186d1ff629a376936e5e3315c051a183c1be6da15500887149a132045cfa394c84871f9c2bb103af3071af629bebe1c53e9cddb121b80f433b2c0a420cf29431f3b41f6b1a960bb307e96f54cb5f888bc5e15f68244778a86c33c7cc40521c4d0ab81da8076ddea2070975edac2e160c4481a7097f23f240ad69e9fe9dfe783bd48f18aa2f3bac237ed2a297cf20c7cb4f1369026c32dd53203767dd7f81c41150947dff716efa5b0c70b84a24afa3934277da1a8adf7b10bc2d8be8a44bdf7a7cfb4e47dd44e3c7b760f362b2c5aa2833b5f963f20d86dd9018a62e94d401cfb843f92b1d7c51f6e6d8fb16cf171476ff04b618a1df0487a3992c9ed91fe1d89933fe3a3f8b3e5c430a18ee6b972788bb70ebe196d9d82b8c8514d1587525f0bcefa364584f6f8e9a3cd4167d43d17af25eb1ec42233d20445bc648b598fa0a56e6d04497c76bbe34c7501952e9587162616ceef2253f39c3853df518af625429d96ce9c52bbc0cbfd05039981d6edce9319132c072eb4453723663988115dd59c34382610956ecbf638a9c295e481f4b3261032f3ac76aa587da9f3d54a2065b2ed5329ffba4e10118ccd8b1b11a7ced79c670725d280837b92a10bc3ca531af47f4afc55759cff250cf5a4a17013cf43ee87b1d9ba817fb9af3db5aac2c708b9ed75265673ab9e99ff93788d7be537d07b59b273c2a9c61c2723fed7700f2c2ace94f284ec6cca8ae893891f7a173c9a5fd3631abe97aff75eb099624fef4cce6e6341ca587c5c144c0dc7d1a8d7ed121baef6d538c00acc046f697f2becf8d8fb49e2a454009e94a8b88291361bfd8f91e2b06426306600b6e95c623cc861920d57ff2f58df33508459d9ab370ce926237901830207bc0be4ec9e419f3102cb01f75da075a034b74350e17b8acedd96a387e75fafbcc2f15b30e7abc29904f586dfcf78af40f9c9ebd4dd4a515ec13407d421a0550cf6faf110a583529bfaa461a3757b6a0e3b26097bcb73267a58b6e6e9028eb5de18675ae9553483447782693137b46dc547a9e52a75ba1d22d5303442cdf85e5eda03d2430cef17210b7ffebfc22369a99f919f818d5ba24656e487c9ec479cb42b053c0479c4abc426688f637caf99fa98b1c361bf9cee7ee907d0ff9b7ab0cee88cf5505075069f300ae1e548a9adada02f39d368bc4dd643cf710e80c1cca5a3d31e42620375ca62b"
  TRIBUNAL_4_USER_DAILY_USAGE_COUNT: "300"
  TRIBUNAL_4_USER_DAILY_USAGE_COST: "2"
  TRIBUNAL_4_DAILY_USAGE_COUNT: "3000"
  TRIBUNAL_4_DAILY_USAGE_COST: "20"

  # TJBA
  TRIBUNAL_12_MODEL: "gemini-2.5-flash,aws-us.anthropic.claude-3-5-haiku-20241022-v1:0,azure-gpt-4.1-mini"
  TRIBUNAL_12_GOOGLE_API_KEY_ENCRYPTED: "78a8ed67400ac02158b1cd09fc32c7cb91a5f44edc16b6cf643151d7b2ec5c82610f4e99bce769afb1f990c840f6acdd706462d6e7da39ae5fa6f8fc180f660f0996f06eb5dbface8c010369cf026d8f1ec288a7a5ba9a66cbab90dc5426593c97826de4f33fd63a5ac7d8d6ad51ca236549e3a3ad1f35dd12b93c9b3e66e2a3735e618f7597d6"
  TRIBUNAL_12_AZURE_API_KEY_ENCRYPTED: "55151d3fc5cdc80b8bece7343c4d08377356cc1b1bcfec0bff1360dc551b8e9310c104b83043ba357b8f699506c49d3ad402ae4d954149fabd32a82c5c13b10b4fddef074f8f80c3b2f15c2f45cdf7f1829f783960d8e98e5cfc2276ccc811f967c25a87b8a82409089d6c748a2e31365432b0221f77a21e76bd04dcc17ac1ca2922fb6bd79c2c963efb199173dcacd0bd3a0cb2fd016fb65b000f76207d66f4d5b991f72f3c49cddd7cc754866a099768ab2f20"
  TRIBUNAL_12_AZURE_RESOURCE_NAME: "https://apoiatjba-dev-eus2-openai.openai.azure.com/openai/deployments"
  TRIBUNAL_12_AWS_SECRET_ACCESS_KEY_ENCRYPTED: "8503bfd9e57207062d3018f42b2522cc6faaac541ed507030097fdd6bd7e75a38a32ef9406b9da4116a904f2e5b4ad06363bce36ded2a43ca848ade1a56a7eeec2a1939559a0f426b32d91d8e1e7d6f350b4d96f2d5f7c9f9822437c641e74ffaab6dfe426595f5498010eaeeabe4c65bd277cb07f17491fa73bc680f95968c48f45a0e5526ca1f9"
  TRIBUNAL_12_AWS_ACCESS_KEY_ID: "AKIAUCPDLVI2EVH5NUG3"
  TRIBUNAL_12_AWS_REGION: "sa-east-1"

  # TJRR
  TRIBUNAL_29_AZURE_API_KEY_ENCRYPTED: "ba24e6c8aedf2de8fd63986a63fecbfcd9676dd05567e271b3ee7fd16a6698c4602dc3e6cb27a5ac9289b20124679a0d0e45c3185e502b8d65ad4da32e1d490c257e6812ba058935bd309c4dda61ab3bf42d0b4e8024b67aa7d8439723733a5c2579b88275468183dac6357c4746c7c5dd876a98a083c08eef139b120989505ce49e19bef6745190a10e4cf317b8c81c243cfb89d792df033fc9a5e16b05da8dffbe9abd34221a88ad21921e867384e5529e2c3d"
  TRIBUNAL_29_MODEL: "azure-gpt-4.1"
  TRIBUNAL_29_AZURE_RESOURCE_NAME: "apoia-1-0-prod"

  # TRE-AP
  TRIBUNAL_13247_AZURE_API_KEY_ENCRYPTED: "4bd2c27b41660fcd493b540deca9651b863e4148225a111a5fe908cdd4a73455f0aafb395c1bc396dbff967ce66d3d5ecae08ef83690c781daa2ad470322e99acedeb12c35a4cd33767d6e9633a7e8bcba3ca767e7b5a034ac452d5ca689439c21c03c770fc3ce949a54c677f69c0f70126f00fae9adba2667ddf6495d38d8d80ad85034dfb9e0ff6474035003f55541528de78f8f54efe3de14ada4f9a05e78cbab793983b47cb501a264afe6882fa03ad1d3a6"
  TRIBUNAL_13247_MODEL: "azure-gpt-4.1-mini"
  TRIBUNAL_13247_AZURE_RESOURCE_NAME: "sti-treap-openai"

  # TRE-ES
  TRIBUNAL_13252_MODEL: "gemini-2.5-flash"
  TRIBUNAL_13252_GOOGLE_API_KEY_ENCRYPTED: "a1d2bf0d41e22b65124ccb130029be61d19515057ff37f81276dc89ebfe25964cb2a0756b6cf00a22b54bf9ea745b845790537f653f070842434d9d9a697b97cb9ea684dbc46174a36b0d12d26a2a92e48b146908f980067c8c4c1d05386c2237e1a841a7117870e852fbb15974e83e9a6d1a7b09ba1b3e691eb424b3e9bbfe71123662926c37f"
  TRIBUNAL_13252_USER_DAILY_USAGE_COUNT: "300"
  TRIBUNAL_13252_USER_DAILY_USAGE_COST: "2"
  TRIBUNAL_13252_DAILY_USAGE_COUNT: "3000"
  TRIBUNAL_13252_DAILY_USAGE_COST: "20"

  # TRE-PR
  TRIBUNAL_13260_MODEL: "gemini-2.5-flash"
  TRIBUNAL_13260_GOOGLE_API_KEY_ENCRYPTED: "6ba0092eaae30b4f8bb31433d29fc525e8d39599f32bcb949894e7c0992e986cb2eff02a8594142cd313942767a05e82bcbeb550ef2e979a2a0bcc6556954a55fc92b48f4fb3ae8f9c00cda02631d1fa7ced8b0335697aaab2acde8bfb2b6b5f3ad9c4a08d581f9ac94a0d710297e789a6719712e4a4a6fd1d1fa94df277b309bbb3d52087f2d8"
  TRIBUNAL_13260_USER_DAILY_USAGE_COUNT: "300"
  TRIBUNAL_13260_USER_DAILY_USAGE_COST: "2"
  TRIBUNAL_13260_DAILY_USAGE_COUNT: "3000"
  TRIBUNAL_13260_DAILY_USAGE_COST: "20"

  # TJMS
  TRIBUNAL_19_AZURE_API_KEY_ENCRYPTED: "7f063bccc4b888cd5ee4e90e926312a5d19c628478adcef38a458cc1ffabcc26d6a843ed31e9dd3171c3287a47dae48fb0888715b244d6ab0f3201b98f5f33936f0c354c0ecae5b6f67f400747998296b94dd4bd8b371e09c87913bab49782745229f3770ebef150f061d13b15db33a266fb651f142dc78cc9654705db6f941d28e8077d1db27ac253101140aab1d71a967a381b0e3c31666566e6b78aeeabb9be67ee9fe0a3895cc10bd811e3fe85d52507c31b"
  TRIBUNAL_19_MODEL: "azure-gpt-4.1-mini"
  TRIBUNAL_19_AZURE_RESOURCE_NAME: "ApoIATJMS"
  TRIBUNAL_19_USER_DAILY_USAGE_COST: "2"
  TRIBUNAL_19_DAILY_USAGE_COST: "40"


  # SYSTEMS: "TRF2,JFRJ,JFES"
  # TRF2_MNI_WSDL_URL: "https://eproc-ws.trf2.jus.br/eproc/wsdl.php?srv=intercomunicacao2.2"
  # TRF2_MNI_ENDPOINT_URL: "https://eproc-ws.trf2.jus.br/eproc/ws/controlador_ws.php?srv=intercomunicacao2.2"
  # JFRJ_MNI_WSDL_URL: "https://eproc-ws.jfrj.jus.br/eproc/wsdl.php?srv=intercomunicacao2.2"
  # JFRJ_MNI_ENDPOINT_URL: "https://eproc-ws.jfrj.jus.br/eproc/ws/controlador_ws.php?srv=intercomunicacao2.2"
  # JFES_MNI_WSDL_URL: "https://eproc-ws.jfes.jus.br/eproc/wsdl.php?srv=intercomunicacao2.2"
  # JFES_MNI_ENDPOINT_URL: "https://eproc-ws.jfes.jus.br/eproc/ws/controlador_ws.php?srv=intercomunicacao2.2"

  PDPJ_JWK: '{"e": "AQAB", "kty": "RSA",  "n": "2lfctxbCT2UWsBMC1rlpmWRcmDRS-EN0opirHzUsgHf7VJCyN0beKchy3biKQeXhgoirWR-f9uufn6Wl_swtua4D-Nw73g6bUCaXHdPWEmNPZb-BML_ebKSJBXCrEMtvOU-LctGKhuNcaAkoYUYVhdVLlQIs_3b6QWtXC8OCJHzIkeKZG9gJX2uon5W8sjU86gOyU7FNdwpZ1-dJmLWiW2YEcXgu4yJfVzg-zHzIriOHASXZC-0luHR-EOtHsC28bg2pLNyrOINO80Mfh4DWhTHcElKOTjc5jll3Y0MjRCML6xTjBzlMFawSKUpzgDvnUgetZDObcafQrk_OY1M9tQ"}'

  SYSTEMS: "JF2R,TRF2,JFRJ,JFES"
  JF2R_KIND: "BALCAOJUS"
  JF2R_API_URL: "https://balcaojus.trf2.jus.br/balcaojus/api/v1"
  TRF2_KIND: "MNI"
  TRF2_MNI_WSDL_URL: "https://eproc-ws.trf2.jus.br/eproc/wsdl.php?srv=intercomunicacao2.2"
  TRF2_MNI_ENDPOINT_URL: "https://eproc-ws.trf2.jus.br/eproc/ws/controlador_ws.php?srv=intercomunicacao2.2"
  JFRJ_KIND: "MNI"
  JFRJ_MNI_WSDL_URL: "https://eproc-ws.jfrj.jus.br/eproc/wsdl.php?srv=intercomunicacao2.2"
  JFRJ_MNI_ENDPOINT_URL: "https://eproc-ws.jfrj.jus.br/eproc/ws/controlador_ws.php?srv=intercomunicacao2.2"
  JFES_KIND: "MNI"
  JFES_MNI_WSDL_URL: "https://eproc-ws.jfes.jus.br/eproc/wsdl.php?srv=intercomunicacao2.2"
  JFES_MNI_ENDPOINT_URL: "https://eproc-ws.jfes.jus.br/eproc/ws/controlador_ws.php?srv=intercomunicacao2.2"
