apiVersion: v1
kind: ConfigMap
metadata:
  name: apoia-config
  labels:
    app: apoia
    part-of: pdpj-apoia
data:
  NEXTAUTH_URL_INTERNAL: "http://localhost:80"
  NEXTAUTH_URL: "http://apoia.stg.pdpj.jus.br"
  ###NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}

  ###JWT_SECRET: ${JWT_SECRET}
  JWT_ISSUER: "apoia.trf2.jus.br"
  JWT_AUDIENCE: "apoia.trf2.jus.br"
  ###PWD_SECRET: ${PWD_SECRET}
  
  COMPLETE_ANALYSIS_LIMIT: "10000"
  CONFIDENTIALITY_LEVEL_MAX: "0"
  VERCEL: "1"
  VERCEL_ENV: "development"
  
  DB_CLIENT: "pg"
  DB_HOST: "postgres.comum-homologacao"
  DB_PORT: "5432"
  #DB_USER: ${DB_USER}
  #DB_PASSWORD: ${DB_PASSWORD}
  DB_DATABASE: "pdpj_apoia"

  ###KEYCLOAK_CREDENTIALS_SECRET: ${KEYCLOAK_CREDENTIALS_SECRET}
  KEYCLOAK_ISSUER: "https://sso.stg.cloud.pje.jus.br/auth/realms/pje"
  
  APP_CODE: "ApoIA"
  APP_HOST: "apoia.stg.pdpj.jus.br"
  APP_PORT: "80"
  APP_REGISTRY_HOST: "discovery.stg.cloud.pje.jus.br/eureka"
  # APP_REGISTRY_PORT: "8761"

  DATALAKE_API_URL: "https://api-processo.stg.data-lake.pdpj.jus.br/processo-api/api/v1"
  
  # SYSTEMS: "TRF2,JFRJ,JFES"
  # TRF2_MNI_WSDL_URL: "https://eproc-ws.trf2.jus.br/eproc/wsdl.php?srv=intercomunicacao2.2"
  # TRF2_MNI_ENDPOINT_URL: "https://eproc-ws.trf2.jus.br/eproc/ws/controlador_ws.php?srv=intercomunicacao2.2"
  # JFRJ_MNI_WSDL_URL: "https://eproc-ws.jfrj.jus.br/eproc/wsdl.php?srv=intercomunicacao2.2"
  # JFRJ_MNI_ENDPOINT_URL: "https://eproc-ws.jfrj.jus.br/eproc/ws/controlador_ws.php?srv=intercomunicacao2.2"
  # JFES_MNI_WSDL_URL: "https://eproc-ws.jfes.jus.br/eproc/wsdl.php?srv=intercomunicacao2.2"
  # JFES_MNI_ENDPOINT_URL: "https://eproc-ws.jfes.jus.br/eproc/ws/controlador_ws.php?srv=intercomunicacao2.2"

  MODERATOR: "00489623760"

  MODEL: "gpt-5-nano"
  OPENAI_API_KEY_ENCRYPTED: "308850fb44833be7faab6c094de4b60961ca97f9e9f1c4c4e3022e71ba80ab47c1718965c161fef6756803322c517207005da3f053eb46b6ca060ebeb896cc2328aca0d6d38dcdd93fcef16d2668c5bb3f59f389f8903cc95b0715d03f527f49f5bb6e5b7020eae83bc61fea82e7d6d6320677595a20fdd7fcf54e6af74c244d2741ed542c8b44f82f78444fc30d16800d2df4c3e8fa02e13180bc954c80517b1ddf859370ee678c60f7f7c1b324b4889a692861ed7318b8a40a46dc491f916d4b9a7645c81baf5f171946653ac04e11cc1c88a708cc735fdfa7fbb828f175d3d883bd8a59228e2956919826315ee4c398f6653b154359dfaca8413abc05b7978cb39bef"

  PDPJ_JWK: '{"e": "AQAB", "kty": "RSA",  "n": "2lfctxbCT2UWsBMC1rlpmWRcmDRS-EN0opirHzUsgHf7VJCyN0beKchy3biKQeXhgoirWR-f9uufn6Wl_swtua4D-Nw73g6bUCaXHdPWEmNPZb-BML_ebKSJBXCrEMtvOU-LctGKhuNcaAkoYUYVhdVLlQIs_3b6QWtXC8OCJHzIkeKZG9gJX2uon5W8sjU86gOyU7FNdwpZ1-dJmLWiW2YEcXgu4yJfVzg-zHzIriOHASXZC-0luHR-EOtHsC28bg2pLNyrOINO80Mfh4DWhTHcElKOTjc5jll3Y0MjRCML6xTjBzlMFawSKUpzgDvnUgetZDObcafQrk_OY1M9tQ"}'
